name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Compilar Java
        run: javac mainn.java
      - name: Ejecutar Java
        run: java mainn
